### ISSUE TITLE
crash (Unexpected token * in JSON at position *)

### ISSUE THREAD

**Issue by mm44** [peers/peerjs-server#112]
Hi, 
after upgrading nodejs, peerserver crashes several times, almost all errors are similar to : 

/srv/node_modules/peer/lib/server.js:111
      throw e;
      ^

SyntaxError: Unexpected token  in JSON at position 113
    at JSON.parse (<anonymous>)
    at WebSocket.<anonymous> (/srv/node_modules/peer/lib/server.js:93:26)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/srv/node_modules/ws/lib/websocket.js:719:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/srv/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/srv/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/srv/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/srv/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:413:12)
error: Forever detected script exited with code: 1

**Comment by mm44** [comment]
10.x (installed from nodesource)

commented this line `throw e;`
is this safe? thanks

**Comment by afrokick** [comment]
Re-open it please if the error occurs again
