### ISSUE TITLE
Does not work on node.js

### ISSUE THREAD

**Issue by fresheneesz** [peers/peerjs-server#144]
I have the following code in `server.js`:

```
var PeerServer = require('peer-server')
const server = PeerServer({port: 9000, path: '/whatever'});
```

Running this gives me:

```
D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:6
"use strict";exports.__esModule=!0,exports.RTCSessionDescription=window.RTCSessionDescription||window.mozRTCSessionDescription,exp
orts.RTCPeerConnection=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection,exports.RTCIceCandida
te=window.RTCIceCandidate||window.mozRTCIceCandidate;
                                                                 ^

ReferenceError: window is not defined
    at Object.parcelRequire.sXtV (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\pe
erjs.min.js:6:66)
    at u (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:1:528)
    at p (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:1:604)
    at Object.parcelRequire.BHXf.js-binarypack (D:\\peerjs\node_modules\peer-server\node_modules\
peerjs\dist\peerjs.min.js:9:217)
    at u (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:1:528)
    at p (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:1:604)
    at Object.parcelRequire.iTK6../util (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\
dist\peerjs.min.js:28:126)
    at u (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.min.js:1:528)
    at parcelRequire.vHo1 (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.mi
n.js:1:827)
    at Object.<anonymous> (D:\\peerjs\node_modules\peer-server\node_modules\peerjs\dist\peerjs.mi
n.js:1:1032)
```

What's going wrong? Please document how to use this in node.js

**Comment by afrokick** [comment]
i can't understand how PeerJS client library occurred on server side?

**Comment by afrokick** [comment]
Please, leave a new comment if you have any questions

**Comment by fresheneesz** [comment]
Looks like I maybe had the wrong package installed (I was using npm peer-server rather than npm peer).
