### ISSUE TITLE
Getting TypeError: Cannot read property 'config' of undefined [middleware/auth/index.js:11:26]

### ISSUE THREAD

**Issue by acrolink** [peers/peerjs-server#162]
I am getting this error running my own `peerjs-server`:

```
TypeError: Cannot read property 'config' of undefined
    at handle (/srv/node/peerjs-server/dist/src/api/middleware/auth/index.js:11:26)
    at Layer.handle [as handle_request] (/srv/node/peerjs-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:317:13)
    at /srv/node/peerjs-server/node_modules/express/lib/router/index.js:284:7
    at param (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:354:14)
    at param (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:365:14)
    at param (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:365:14)
    at param (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:410:3)
    at next (/srv/node/peerjs-server/node_modules/express/lib/router/index.js:275:10)
```

On the browser console log I get:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://my.domain.com:9000/peerjs/peerjs/2fe858b9-d3cf-431a-ba61-b39e11e77e80/vlsv2lkgce/id?i=0
```

**Comment by acrolink** [comment]
Error was due to using old version of `PeerJS`
