### ISSUE TITLE
Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by riscoss63** [peers/peerjs-server#165]
Hi i have an error with peerserver :

```
TypeError: Cannot read property 'config' of undefined
    at handle (/var/www/peerServer/node_modules/peer/dist/src/api/middleware/auth/index.js:11:26)

    at Layer.handle [as handle_request] (/var/www/peerServer/node_modules/express/lib/router/layer.js:95:5)

    at trim_prefix (/var/www/peerServer/node_modules/express/lib/router/index.js:317:13)

    at /var/www/peerServer/node_modules/express/lib/router/index.js:284:7

    at param (/var/www/peerServer/node_modules/express/lib/router/index.js:354:14)

    at param (/var/www/peerServer/node_modules/express/lib/router/index.js:365:14)

    at param (/var/www/peerServer/node_modules/express/lib/router/index.js:365:14)

    at param (/var/www/peerServer/node_modules/express/lib/router/index.js:365:14)

    at Function.process_params (/var/www/peerServer/node_modules/express/lib/router/index.js:410:3)

    at next (/var/www/peerServer/node_modules/express/lib/router/index.js:275:10)
```

This my config:
 -to launche peerserver: 

`./peerjs --port 9000 --key peerjs --sslkey /etc/letsencrypt/live/peerserver.xxx.com/privkey.pem --sslcert /etc/letsencrypt/live/peerserver.xxx.com/fullchain.pem --path /myapp`

 -to connect:

 `var peer = new Peer({
        key: 'peerjs',
        host: 'peerserver.xxx.com',
        port: 9000,
        path: '/myapp',
        secure: true,
        debug: 3,
        config: {
            "iceServers": [     // Information about ICE servers - Use your own!
            {
                "urls": "stun:turn.mysite.com",
                "username": "xxx",
                "credential": "xxx"
            },
            {
                "urls": "turn:turn.mysite.com",
                "username": "xxx",
                "credential": "xxx"
            },
            ]
        }
    })`

Thank you

**Comment by afrokick** [comment]
Which versions do you use?

**Comment by riscoss63** [comment]
Thank you for your reply. I use the latest version, download on github.

**Comment by afrokick** [comment]
Give me a few minutes, i'll fix it and release. Thank you a lot @riscoss63

**Comment by riscoss63** [comment]
Thank you very muche you are the best

**Comment by afrokick** [comment]
@riscoss63 please try the latest version from GitHub or from npm `npm i peer@0.5.0`
